- systemd:
    name: openresty
    state: stopped
  ignore_errors: yes

- stat: path=/usr/local/openresty
  register: var_openresty_folder
- name: "Copy openresty.tar.gz to target deployment machine"
  synchronize:
   src: /tmp/openresty.tar.gz
   dest: /usr/local/openresty.tar.gz
  when: not var_openresty_folder.stat.exists
- name: "cd /usr/local && tar zxf openresty.tar.gz"
  shell: cd /usr/local && tar zxf openresty.tar.gz
  when: not var_openresty_folder.stat.exists
- file:
   path: /usr/local/openresty.tar.gz
   state: absent

- name: "Copy file openresty.service to /usr/lib/systemd/system/openresty.service"
  template:
    src: openresty.service
    dest: /usr/lib/systemd/system/openresty.service
- name: "Copy file naxsi.rules to /usr/local/openresty/nginx/conf/naxsi.rules"
  template:
    src: naxsi.rules
    dest: /usr/local/openresty/nginx/conf/naxsi.rules
- name: "Copy file nginx.conf to /usr/local/openresty/nginx/conf/nginx.conf"
  template:
    src: nginx.conf
    dest: /usr/local/openresty/nginx/conf/nginx.conf

- name: "systemctl restart openresty"
  systemd:
    name: openresty
    state: restarted
