---

# Install necessary compile component
- name: "yum install make readline-devel pcre-devel openssl-devel gcc perl"
  yum:
    name: make,readline-devel,pcre-devel,openssl-devel,gcc,perl
    state: installed

# Download and prepare openresty, naxsi source code
- name: "Download openresty source code from url https://bucket-public-common.oss-cn-hangzhou.aliyuncs.com/nginx/openresty-1.15.8.1.tar.gz"
  get_url:
    url: https://bucket-public-common.oss-cn-hangzhou.aliyuncs.com/nginx/openresty-1.15.8.1.tar.gz
    dest: /tmp/openresty-1.15.8.1.tar.gz
- name: "Download naxsi source code from url https://bucket-public-common.oss-cn-hangzhou.aliyuncs.com/nginx/naxsi-0.56.tar.gz"
  get_url:
    url: https://bucket-public-common.oss-cn-hangzhou.aliyuncs.com/nginx/naxsi-0.56.tar.gz
    dest: /tmp/naxsi-0.56.tar.gz

- name: "Remove /tmp/openresty-1.15.8.1 folder"
  file:
    path: /tmp/openresty-1.15.8.1
    state: absent
- name: "Remove /tmp/naxsi-0.56 folder"
  file:
    path: /tmp/naxsi-0.56
    state: absent

- name: "cd /tmp && tar -xzf openresty-1.15.8.1.tar.gz"
  shell: cd /tmp && tar -xzf openresty-1.15.8.1.tar.gz
- name: "cd /tmp && tar -xzf naxsi-0.56.tar.gz"
  shell: cd /tmp && tar -xzf naxsi-0.56.tar.gz

- name: "cd /tmp/openresty-1.15.8.1 && ./configure --add-module=/tmp/naxsi-0.56/naxsi_src"
  shell: cd /tmp/openresty-1.15.8.1 && ./configure --add-module=/tmp/naxsi-0.56/naxsi_src
- name: "cd /tmp/openresty-1.15.8.1 && make install"
  shell: cd /tmp/openresty-1.15.8.1 && make install

- name: "cp -nf /tmp/naxsi-0.56/naxsi_config/naxsi_core.rules /usr/local/openresty/nginx/conf/naxsi_core.rules"
  shell: cp -nf /tmp/naxsi-0.56/naxsi_config/naxsi_core.rules /usr/local/openresty/nginx/conf/naxsi_core.rules

- name: "Copy file openresty.service to /usr/lib/systemd/system/openresty.service"
  template:
    src: openresty.service
    dest: /usr/lib/systemd/system/openresty.service
- name: "Copy file naxsi.rules to /usr/local/openresty/nginx/conf/naxsi.rules"
  template:
    src: naxsi.rules
    dest: /usr/local/openresty/nginx/conf/naxsi.rules
- name: "Copy file nginx.conf to /usr/local/openresty/nginx/conf/nginx.conf"
  template:
    src: nginx.conf
    dest: /usr/local/openresty/nginx/conf/nginx.conf
