---
- name: Install freeswitch server
  hosts: all
  become: yes
  roles:
    - role: role_os_timezone
    - role: role_os_firewall
    - role: role_freeswitch_install
      var_socks5: "{{ socks5 | default('') }}"