---

- name: "When var_socks5 is defined remove line startwith proxy=socks5 firstly"
  lineinfile:
   path: /etc/yum.conf
   regexp: "proxy=socks5"
   state: absent
  when: var_socks5|length>0
- name: "When var_socks5 is defined remove line startwith #proxy=socks5 firstly"
  lineinfile:
   path: /etc/yum.conf
   regexp: "#proxy=socks5"
   state: absent
  when: var_socks5|length>0
- name: "When var_socks5 is defined setup yum socks5 proxy in /etc/yum.conf file"
  lineinfile:
    path: /etc/yum.conf
    line: "proxy={{ var_socks5 }}"
    state: present
  when: var_socks5|length>0

- name: Download freeswitch-release-repo-0-1.noarch.rpm
  get_url:
   url: https://files.freeswitch.org/repo/yum/centos-release/freeswitch-release-repo-0-1.noarch.rpm
   dest: /tmp/freeswitch-release-repo-0-1.noarch.rpm

- name: Install freeswitch official yum repository
  yum:
    name: /tmp/freeswitch-release-repo-0-1.noarch.rpm
    state: installed

- name: yum install freeswitch-config-vanilla
  yum:
    name: freeswitch-config-vanilla
    state: installed

- name: Remove yum socks5 proxy configuration in /etc/yum.conf file
  lineinfile:
    path: /etc/yum.conf
    regexp: "proxy=socks5"
    state: absent

- name: "Replace default_password=1234 in /etc/freeswitch/vars.xml"
  replace:
    path: /etc/freeswitch/vars.xml
    regexp: default_password=1234
    replace: default_password={{ var_default_password }}
  when: var_default_password is defined and var_default_password|length>0

- name: "Modify external_auth_calls=true in /etc/freeswitch/vars.xml"
  replace:
    path: /etc/freeswitch/vars.xml
    regexp: external_auth_calls=false
    replace: external_auth_calls=true

- name: "Modify external_rtp_ip=stun:stun.freeswitch.org"
  replace:
   path: /etc/freeswitch/vars.xml
   regexp: "external_rtp_ip=stun:stun.freeswitch.org"
   replace: "external_rtp_ip={{ var_external_ip }}"
  when: var_external_ip is defined and var_external_ip|length>0
- name: "Modify external_sip_ip=stun:stun.freeswitch.org"
  replace:
   path: /etc/freeswitch/vars.xml
   regexp: "external_sip_ip=stun:stun.freeswitch.org"
   replace: "external_sip_ip={{ var_external_ip }}"
  when: var_external_ip is defined and var_external_ip|length>0

- name: "Modify internal_sip_port"
  replace:
   path: /etc/freeswitch/vars.xml
   regexp: "internal_sip_port=5060"
   replace: "internal_sip_port={{ var_listen_port }}"
  when: var_listen_port is defined and var_listen_port|length>0

- name: "Modify log-auth-failures=true in /etc/freeswitch/sip_profiles/internal.xml"
  replace:
    path: /etc/freeswitch/sip_profiles/internal.xml
    regexp: '<param name="log-auth-failures" value="false"/>'
    replace: '<param name="log-auth-failures" value="true"/>'

- name: "Remove ipv6 support"
  shell: rm -rf /etc/freeswitch/sip_profiles/*ipv6*

- name: "Modify listen-ip=127.0.0.1 in /etc/freeswitch/autoload_configs/event_socket.conf.xml"
  replace:
    path: /etc/freeswitch/autoload_configs/event_socket.conf.xml
    regexp: value="::"
    replace: value="127.0.0.1"

- name: "Replace target /etc/freeswitch/autoload_configs/acl.conf.xml with template acl.conf.xml"
  template:
   src: acl.conf.xml
   dest: /etc/freeswitch/autoload_configs/acl.conf.xml
   group: daemon
   owner: freeswitch
   mode: u=rw,g=r
- shell: cat /etc/freeswitch/sip_profiles/internal.xml | grep '^<param name="apply-inbound-acl" value="twilio"/>' | wc -l
  register: var_result
- name: 'Config twilio acl'
  lineinfile:
   path: /etc/freeswitch/sip_profiles/internal.xml
   insertbefore: </settings>
   line: <param name="apply-inbound-acl" value="twilio"/>
  when: var_result.stdout == "0"

- shell: cat /etc/freeswitch/sip_profiles/internal.xml | grep '^<param name="apply-inbound-acl" value="voxbone"/>' | wc -l
  register: var_result
- name: 'Config voxbone acl'
  lineinfile:
   path: /etc/freeswitch/sip_profiles/internal.xml
   insertbefore: </settings>
   line: <param name="apply-inbound-acl" value="voxbone"/>
  when: var_result.stdout == "0"

- shell: cat /etc/freeswitch/sip_profiles/internal.xml | grep '^<param name="apply-inbound-acl" value="cm"/>' | wc -l
  register: var_result
- name: 'Config cm acl'
  lineinfile:
   path: /etc/freeswitch/sip_profiles/internal.xml
   insertbefore: </settings>
   line: <param name="apply-inbound-acl" value="cm"/>
  when: var_result.stdout == "0"

# Install sngrep
- name: "Copy sngrep.repo file to /etc/yum.repos.d/sngrep.repo"
  template:
   src: sngrep.repo
   dest: /etc/yum.repos.d/sngrep.repo
- name: "rpm --import http://packages.irontec.com/public.key"
  shell: rpm --import http://packages.irontec.com/public.key
- name: "yum install -y sngrep"
  yum:
   name: sngrep
   state: installed

- name: "systemctl enable freeswitch"
  systemd:
   name: freeswitch
   enabled: yes

- name: "systemctl restart freeswitch"
  systemd:
   name: freeswitch
   state: restarted

# Install fail2ban
- name: "yum install fail2ban"
  yum:
   name: fail2ban
   state: installed
- name: "Delete /etc/fail2ban/jail.d/00-firewalld.conf"
  file:
   path: /etc/fail2ban/jail.d/00-firewalld.conf
   state: absent
- name: "Copy freeswitch.local"
  template:
   src: freeswitch.local
   dest: /etc/fail2ban/jail.d/freeswitch.local
- name: "systemctl enable fail2ban"
  systemd:
   name: fail2ban
   enabled: yes
- name: "systemctl restart fail2ban"
  systemd:
   name: fail2ban
   state: restarted