---
# 安装intellJ IDEA开发工具
- file:
   name: /usr/local/intelliJ-IDEA
   state: directory
- stat:
   path: /usr/local/intelliJ-IDEA/idea-IC-193.6911.18
  register: ideaFolderVar
- get_url:
   url: https://bucketxy.oss-cn-hangzhou.aliyuncs.com/intelliJ-IDEA/ideaIC-2019.3.4.tar.gz
   dest: /usr/local/intelliJ-IDEA/ideaIC-2019.3.4.tar.gz
  when: not ideaFolderVar.stat.exists
- shell: cd /usr/local/intelliJ-IDEA && tar -xvzf ideaIC-2019.3.4.tar.gz
  when: not ideaFolderVar.stat.exists
- file:
   name: /usr/local/intelliJ-IDEA/ideaIC-2019.3.4.tar.gz
   state: absent
- file:
   name: /root/.m2
   state: directory
- copy:
   src: ./settings.xml
   dest: /root/.m2/settings.xml