---
# 安装 smartgit
- stat:
   path: /usr/local/smartgit
  register: smartgitFolderVar
- get_url:
   url: https://bucketxy.oss-cn-hangzhou.aliyuncs.com/smartgit/smartgit-linux-20_2_0.tar.gz
   dest: /usr/local/smartgit-linux-20_2_0.tar.gz
  when: not smartgitFolderVar.stat.exists
- shell: cd /usr/local && tar -xvzf smartgit-linux-20_2_0.tar.gz
  when: not smartgitFolderVar.stat.exists
- file:
   name: /usr/local/smartgit-linux-20_2_0.tar.gz
   state: absent